# Generated by Django 4.1.3 on 2022-11-08 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(max_length=50, verbose_name='Город')),
                ('street', models.TextField(max_length=50, verbose_name='Улица')),
                ('house', models.TextField(max_length=10, verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Эл. почта')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_address_set', to='SalesNetwork.address')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Дилерский центр',
                'verbose_name_plural': 'Дилерские центры',
            },
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Дистрибьютор',
                'verbose_name_plural': 'Дистрибьюторы',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Завод',
                'verbose_name_plural': 'Заводы',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Название продукта')),
                ('model', models.TextField(max_length=50, verbose_name='Модель')),
                ('release_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='ФИО работника')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='SellersNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True, verbose_name='Название компании')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Долг')),
                ('creation_time', models.DateTimeField(auto_now=True, verbose_name='Дата и время создания')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_contacts_set', to='SalesNetwork.contacts', verbose_name='Контакты')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_products_set', to='SalesNetwork.products', verbose_name='Продукты')),
                ('workers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_workers_set', to='SalesNetwork.workers', verbose_name='Работники')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информация',
            },
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealership_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_to_ret_set', to='SalesNetwork.dealership', verbose_name='Поставщик <Дилерский центр>')),
                ('distributor_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dist_to_ret_set', to='SalesNetwork.distributor', verbose_name='Поставщик <Дистрибьютор>')),
                ('factory_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fact_to_ret_set', to='SalesNetwork.factory', verbose_name='Поставщик <Завод>')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_info_set', to='SalesNetwork.sellersnetwork', verbose_name='Крупная розничная сеть')),
            ],
            options={
                'verbose_name': 'Розничная сеть',
                'verbose_name_plural': 'Розничные сети',
            },
        ),
        migrations.CreateModel(
            name='IndividualSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealership_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_to_ind_set', to='SalesNetwork.dealership', verbose_name='Поставщик <Дилерский центр>')),
                ('distributor_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dist_to_ind_set', to='SalesNetwork.distributor', verbose_name='Поставщик <Дистрибьютор>')),
                ('factory_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fact_to_ind_set', to='SalesNetwork.factory', verbose_name='Поставщик <Завод>')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers_info_set', to='SalesNetwork.sellersnetwork', verbose_name='ИП')),
                ('retailer_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ret_to_ind_set', to='SalesNetwork.dealership', verbose_name='Поставщик <Розничная сеть>')),
            ],
            options={
                'verbose_name': 'ИП',
                'verbose_name_plural': 'ИП',
            },
        ),
        migrations.AddField(
            model_name='factory',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_info_set', to='SalesNetwork.sellersnetwork', verbose_name='Завод'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='factory_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fact_to_dist_set', to='SalesNetwork.factory', verbose_name='Поставщик <Завод>'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_info_set', to='SalesNetwork.sellersnetwork', verbose_name='Дистрибьютор'),
        ),
        migrations.AddField(
            model_name='dealership',
            name='distributor_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dist_to_deal_set', to='SalesNetwork.distributor', verbose_name='Поставщик <Дистрибьютор>'),
        ),
        migrations.AddField(
            model_name='dealership',
            name='factory_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fact_to_deal_set', to='SalesNetwork.factory', verbose_name='Поставщик <Завод>'),
        ),
        migrations.AddField(
            model_name='dealership',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealership_info_set', to='SalesNetwork.sellersnetwork', verbose_name='Дилерский центр'),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_address_set', to='SalesNetwork.country'),
        ),
    ]
