# Generated by Django 4.1.3 on 2022-11-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesNetwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='is_working_now',
            field=models.BooleanField(default=True, verbose_name='Работает сейчас'),
        ),
        migrations.RemoveField(
            model_name='sellersnetwork',
            name='workers',
        ),
        migrations.AddField(
            model_name='sellersnetwork',
            name='workers',
            field=models.ManyToManyField(db_index=True, related_name='info_workers_set', to='SalesNetwork.workers', verbose_name='Работники'),
        ),
    ]
