# Generated by Django 4.1.3 on 2022-11-11 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SalesNetwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersnetwork',
            name='workers',
            field=models.ManyToManyField(db_index=True, related_name='info_workers_set', to=settings.AUTH_USER_MODEL, verbose_name='Работники'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='dealership_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_to_ret_set', to='SalesNetwork.dealership', verbose_name='Поставщик <Дилерский центр>'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='distributor_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dist_to_ret_set', to='SalesNetwork.distributor', verbose_name='Поставщик <Дистрибьютор>'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='factory_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fact_to_ret_set', to='SalesNetwork.factory', verbose_name='Поставщик <Завод>'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_info_set', to='SalesNetwork.sellersnetwork', verbose_name='Крупная розничная сеть'),
        ),
        migrations.AddField(
            model_name='individualseller',
            name='dealership_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_to_ind_set', to='SalesNetwork.dealership', verbose_name='Поставщик <Дилерский центр>'),
        ),
        migrations.AddField(
            model_name='individualseller',
            name='distributor_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dist_to_ind_set', to='SalesNetwork.distributor', verbose_name='Поставщик <Дистрибьютор>'),
        ),
        migrations.AddField(
            model_name='individualseller',
            name='factory_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fact_to_ind_set', to='SalesNetwork.factory', verbose_name='Поставщик <Завод>'),
        ),
        migrations.AddField(
            model_name='individualseller',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers_info_set', to='SalesNetwork.sellersnetwork', verbose_name='ИП'),
        ),
        migrations.AddField(
            model_name='individualseller',
            name='retailer_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ret_to_ind_set', to='SalesNetwork.dealership', verbose_name='Поставщик <Розничная сеть>'),
        ),
        migrations.AddField(
            model_name='factory',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_info_set', to='SalesNetwork.sellersnetwork', verbose_name='Завод'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='factory_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fact_to_dist_set', to='SalesNetwork.factory', verbose_name='Поставщик <Завод>'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_info_set', to='SalesNetwork.sellersnetwork', verbose_name='Дистрибьютор'),
        ),
        migrations.AddField(
            model_name='dealership',
            name='distributor_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dist_to_deal_set', to='SalesNetwork.distributor', verbose_name='Поставщик <Дистрибьютор>'),
        ),
        migrations.AddField(
            model_name='dealership',
            name='factory_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fact_to_deal_set', to='SalesNetwork.factory', verbose_name='Поставщик <Завод>'),
        ),
        migrations.AddField(
            model_name='dealership',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealership_info_set', to='SalesNetwork.sellersnetwork', verbose_name='Дилерский центр'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_address_set', to='SalesNetwork.address'),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_address_set', to='SalesNetwork.country'),
        ),
    ]
