# Generated by Django 4.1.3 on 2022-11-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesNetwork', '0002_workers_is_working_now_remove_sellersnetwork_workers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellersnetwork',
            name='products',
        ),
        migrations.AddField(
            model_name='sellersnetwork',
            name='products',
            field=models.ManyToManyField(db_index=True, related_name='info_products_set', to='SalesNetwork.products', verbose_name='Продукты'),
        ),
    ]
