# Generated by Django 4.1.3 on 2022-11-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesNetwork', '0004_rename_model_products_prod_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellersnetwork',
            name='name',
            field=models.TextField(max_length=50, verbose_name='Название компании'),
        ),
    ]
